apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          image: 039612866426.dkr.ecr.ap-south-1.amazonaws.com/searchsvc:latest
          ports:
            - containerPort: 9093

---
apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: default
spec:
  selector:
    app: search-service
  ports:
    - protocol: TCP
      port: 9093
      targetPort: 9093
  type: ClusterIP

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: search-service
spec:
  hosts:
    - "*"
  gateways:
    - istio-ingressgateway
  http:
    - match:
        - uri:
            prefix: /search
      route:
        - destination:
            host: search-service.default.svc.cluster.local
            port:
              number: 9093